project_id = "pollapp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[local_smtp]
enabled = false

[storage]
enabled = false

[auth]
enabled = true

[edge_runtime]
enabled = false

[analytics]
enabled = false
